version: "3.9"

services:

  maildev:
    image: maildev/maildev
    ports:
      - "1080:1080"
      - "1025:1025"

  financetracker:
    build: .
    environment:
      WAIT_HOSTS: postgres:5432, maildev:1025