spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/financetracker
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: http://localhost:8180/realms/finance

server:
  servlet:
    context-path: /api/v1
  error:
    include-message: always

springdoc:
  api-docs:
    path: /api-docs